import type { SupabaseClient } from "@supabase/supabase-js";
import type { ScoredState, ScoredSignal } from "./types.js";
import { SCORING_VERSION } from "./types.js";
import { resolvePack, checkSynthesisGate } from "../packs/resolve.js";
import { FAMILY_DISPLAY, type QuestionType, type SourcePack } from "../packs/index.js";
import { computeSourceComparison, expertLineFromComparison } from "./synthesis.js";
import { phraseSynthesis, isLayerBEnabled } from "./synthesis-phrasing.js";
import type { Logger } from "@signal-map/logger";

interface TopicRow {
  id: string;
  canonical_name: string;
  slug: string;
  category: string | null;
}

interface PublishedSnapshot {
  id: string;
  version: number;
}

/**
 * 5-step snapshot publication transaction (hard invariant).
 * All steps must succeed or snapshot must not become latest.
 * Realtime/invalidation emitted ONLY after all steps complete.
 */
export async function publishSnapshot(
  supabase: SupabaseClient,
  topic: TopicRow,
  state: ScoredState,
  signals: ScoredSignal[],
  logger?: Logger,
): Promise<PublishedSnapshot> {
  const now = new Date().toISOString();

  // Step 0: Carry forward prose from previous snapshot (so it's never lost)
  // Prose comes from LLM summarization (async) or manual seeding. Without this,
  // every new snapshot would wipe the prose until summarization re-runs.
  interface ProseFields { current_picture_text: string | null; what_changed_text: string | null; what_next_text: string | null }
  let carryProse: ProseFields = { current_picture_text: null, what_changed_text: null, what_next_text: null };
  const { data: prevPointer } = await supabase
    .from("topic_latest_snapshot")
    .select("snapshot_id")
    .eq("topic_id", topic.id)
    .maybeSingle();
  if (prevPointer) {
    const { data: prev } = await supabase
      .from("topic_snapshots")
      .select("current_picture_text, what_changed_text, what_next_text")
      .eq("id", (prevPointer as { snapshot_id: string }).snapshot_id)
      .single();
    if (prev) carryProse = prev as ProseFields;
  }

  // Step 1: Get next version (per-topic monotonic)
  const { data: maxVersionRow } = await supabase
    .from("topic_snapshots")
    .select("version")
    .eq("topic_id", topic.id)
    .order("version", { ascending: false })
    .limit(1)
    .maybeSingle();

  const version =
    ((maxVersionRow as { version: number } | null)?.version ?? 0) + 1;

  // Step 2: INSERT snapshot row (carrying forward prose from previous)
  const { data: snapshot, error: snapError } = await supabase
    .from("topic_snapshots")
    .insert({
      topic_id: topic.id,
      version,
      direction: state.direction,
      confidence: state.confidence,
      disagreement: state.disagreement,
      freshness: state.freshness,
      staleness_seconds: state.stalenessSeconds,
      structured_data: state.structuredData,
      scoring_version: SCORING_VERSION,
      snapshot_at: now,
      published_at: now,
      current_picture_text: carryProse.current_picture_text,
      what_changed_text: carryProse.what_changed_text,
      what_next_text: carryProse.what_next_text,
    })
    .select("id")
    .single();

  if (snapError || !snapshot) {
    throw new Error(
      `Failed to insert snapshot: ${snapError?.message ?? "no data"}`,
    );
  }

  const snapshotId = (snapshot as { id: string }).id;

  // Step 3: INSERT topic_signals (snapshot-bound, append-only)
  if (signals.length > 0) {
    const signalRows = signals.map((s) => ({
      topic_id: topic.id,
      snapshot_id: snapshotId,
      source_family: s.sourceFamily,
      source_name: s.sourceName,
      signal_type: s.signalType,
      current_value: s.currentValue,
      previous_value: s.previousValue,
      delta: s.delta,
      direction: s.direction,
      weight: s.weight,
      freshness: s.freshness,
      external_id: s.externalId,
      metadata: s.metadata,
    }));

    const { error: sigError } = await supabase
      .from("topic_signals")
      .insert(signalRows);

    if (sigError) {
      throw new Error(`Failed to insert signals: ${sigError.message}`);
    }
  }

  // Step 4: UPSERT topic_latest_snapshot pointer
  const { error: latestError } = await supabase
    .from("topic_latest_snapshot")
    .upsert({
      topic_id: topic.id,
      snapshot_id: snapshotId,
    });

  if (latestError) {
    throw new Error(
      `Failed to update latest pointer: ${latestError.message}`,
    );
  }

  // Step 5: UPSERT public_topic_cards (deterministic, no LLM dependency)
  // Preserve hand-written one-liners: only overwrite if existing is a generic template
  const computedOneLiner = generateDeterministicOneLiner(state, signals, topic.canonical_name);

  // Patterns that indicate a COMPUTED one-liner (generated by this function)
  // vs a HAND-WRITTEN one (curated, should be preserved)
  const COMPUTED_PATTERNS = [
    // Generic fallbacks
    "We're watching", "We're gathering", "We are tracking",
    "Following industry", "Monitoring international", "Watching trends",
    "Tracking odds", "Early signals", "Signals are pointing",
    // Deterministic generator outputs
    "Markets see this as unlikely",
    "Markets are pricing this at",
    "Crude oil is holding at",
    "is holding at", // matches "The federal funds rate is holding at..."
    "Multiple legislative actions detected",
    "Limited legislative activity",
    "with no significant movement",
    "No clear direction right now",
    "earthquakes recorded recently",
    "NWS weather alerts are active",
    "showing upward momentum. Market sentiment",
    "showing downward pressure. Market sentiment",
    "Tracking ", // matches "Tracking X data points"
  ];

  const { data: existingCard } = await supabase
    .from("public_topic_cards")
    .select("one_liner")
    .eq("topic_id", topic.id)
    .maybeSingle();

  const existingOneLiner = (existingCard as { one_liner: string | null } | null)?.one_liner;
  const existingIsComputed = !existingOneLiner || existingOneLiner.length < 40 ||
    COMPUTED_PATTERNS.some((p) => existingOneLiner.includes(p));

  const oneLiner = existingIsComputed ? computedOneLiner : existingOneLiner;

  // ── Synthesis gate: compute source diversity + pack eligibility ──

  // Count source families
  const familyCounts = new Map<string, number>();
  for (const s of signals) {
    familyCounts.set(s.sourceFamily, (familyCounts.get(s.sourceFamily) ?? 0) + 1);
  }
  const sourceFamilies = [...familyCounts.keys()];
  const sourceFamilyCount = sourceFamilies.length;
  const signalCount = signals.length;

  // Resolve question type: prefer explicit from questions table, fall back to derived
  let questionType: QuestionType | null = null;
  const { data: questionRow } = await supabase
    .from("questions")
    .select("question_type")
    .eq("primary_topic_id", topic.id)
    .eq("status", "published")
    .limit(1)
    .maybeSingle();

  if (questionRow) {
    const qt = (questionRow as { question_type: string | null }).question_type;
    if (qt === "binary_event" || qt === "threshold" || qt === "competition") {
      questionType = qt;
    }
  }
  // Fallback: derive from category
  if (!questionType) {
    if (topic.category === "sports") questionType = "competition";
    else if (topic.category === "macro" || topic.category === "crypto") questionType = "threshold";
    else questionType = "binary_event";
  }

  // Resolve pack and check gate
  const pack = resolvePack(questionType, topic.category);
  const synthesisReady = pack
    ? checkSynthesisGate(pack, signals.map((s) => ({ source_family: s.sourceFamily, source_name: s.sourceName })))
    : false;

  // Compute structured source comparison (deterministic, no LLM)
  const sourceComparison = (synthesisReady && pack)
    ? computeSourceComparison(signals, pack, questionType, topic.slug, state.direction)
    : null;

  // Generate expert line: prefer comparison-driven, fall back to template-based
  const comparisonExpertLine = sourceComparison
    ? expertLineFromComparison(sourceComparison)
    : null;
  const expertLine = comparisonExpertLine
    ?? (pack ? generateExpertLine(signals, pack, questionType, state.direction, state.confidence) : null);

  // Extract competition leader/challenger from live signals
  let competitionLeader: string | null = null;
  let competitionLeaderPct: number | null = null;
  let competitionChallenger: string | null = null;
  let competitionGap: number | null = null;

  if (questionType === "competition") {
    const ranking = extractCompetitionRanking(signals);
    const leader = ranking[0] ?? null;
    const challenger = ranking[1] ?? null;
    if (leader) {
      competitionLeader = leader.name;
      competitionLeaderPct = leader.pct;
    }
    if (leader && challenger) {
      competitionChallenger = challenger.name;
      competitionGap = leader.pct - challenger.pct;
    }
  }

  const { error: cardError } = await supabase
    .from("public_topic_cards")
    .upsert({
      topic_id: topic.id,
      canonical_name: topic.canonical_name,
      slug: topic.slug,
      category: topic.category,
      direction: state.direction,
      confidence: state.confidence,
      freshness: state.freshness,
      one_liner: oneLiner,
      snapshot_published_at: now,
      // Synthesis gate fields
      source_family_count: sourceFamilyCount,
      source_families: sourceFamilies,
      signal_count: signalCount,
      synthesis_ready: synthesisReady,
      expert_line: expertLine,
      synthesis_json: sourceComparison,
      // Live competition data
      competition_leader: competitionLeader,
      competition_leader_pct: competitionLeaderPct,
      competition_challenger: competitionChallenger,
      competition_gap: competitionGap,
    });

  if (cardError) {
    throw new Error(`Failed to update topic card: ${cardError.message}`);
  }

  // Write synthesis_json to snapshot too (for detail page rendering)
  if (sourceComparison) {
    await supabase
      .from("topic_snapshots")
      .update({ synthesis_json: sourceComparison })
      .eq("id", snapshotId);
  }

  // Layer B: constrained LLM phrasing (whitelisted pages only)
  if (sourceComparison && logger && isLayerBEnabled(topic.slug)) {
    const questionRow = await supabase
      .from("questions")
      .select("question_text")
      .eq("primary_topic_id", topic.id)
      .eq("status", "published")
      .limit(1)
      .maybeSingle();
    const qText = (questionRow.data as { question_text: string } | null)?.question_text ?? topic.canonical_name;

    const phrased = await phraseSynthesis(sourceComparison, qText, topic.slug, logger);
    if (phrased) {
      // Write phrased synthesis to snapshot + card
      await supabase.from("topic_snapshots")
        .update({ synthesis_phrased: phrased })
        .eq("id", snapshotId);
      await supabase.from("public_topic_cards")
        .update({
          synthesis_phrased: phrased,
          expert_line: phrased.bottom_line, // homepage card uses phrased bottom line
        })
        .eq("topic_id", topic.id);
    }
  }

  return { id: snapshotId, version };
}

// ── Deterministic One-Liner Generation ──
// These must read like a smart friend answering a question, NOT like a data report.
// The one-liner IS the product for 80% of users. They scan it and leave.

/** Human-readable context for macro data series */
const MACRO_CONTEXT: Record<string, { name: string; unit: string; context: string }> = {
  MORTGAGE30US: { name: "mortgage rates", unit: "%", context: "The 30-year fixed rate" },
  CPIAUCSL: { name: "consumer prices", unit: "", context: "The consumer price index" },
  UNRATE: { name: "unemployment", unit: "%", context: "The unemployment rate" },
  FEDFUNDS: { name: "the Fed rate", unit: "%", context: "The federal funds rate" },
  DGS10: { name: "Treasury yields", unit: "%", context: "The 10-year Treasury yield" },
  GDP: { name: "economic growth", unit: "", context: "GDP" },
  CES0000000001: { name: "job creation", unit: "", context: "Nonfarm payrolls" },
  LNS14000000: { name: "unemployment", unit: "%", context: "The unemployment rate" },
  "CUSR0000SA0": { name: "consumer prices", unit: "", context: "The consumer price index" },
  "CUUR0000SA0": { name: "consumer prices", unit: "", context: "The consumer price index" },
  "PET.RWTC.W": { name: "oil prices", unit: "", context: "Crude oil" },
};

function generateDeterministicOneLiner(
  state: ScoredState,
  signals: ScoredSignal[],
  topicName: string = "",
): string {
  const primary = signals
    .filter((s) => s.currentValue !== null && s.currentValue !== undefined)
    .sort((a, b) => b.weight - a.weight)[0];

  const signalCount = signals.length;
  const dir = state.direction;

  // ── Macro official: translate data into plain language ──
  if (primary && primary.sourceFamily === "macro_official") {
    const seriesId = String(primary.metadata?.series_id ?? "");
    const ctx = MACRO_CONTEXT[seriesId];
    const value = Number(primary.currentValue);
    const delta = primary.delta !== null ? Number(primary.delta) : null;

    if (ctx) {
      const valueStr = ctx.unit === "%" ? `${value > 10 ? value.toFixed(1) : value.toFixed(2)}%` : value.toLocaleString("en-US");

      if (delta !== null && Math.abs(delta) > 0.01) {
        const movement = delta > 0 ? "edged higher" : "moved lower";
        return `${ctx.context} is at ${valueStr} and has ${movement} recently. ${signalCount > 1 ? `Tracking ${signalCount} data points.` : ""}`.trim();
      }
      return `${ctx.context} is holding at ${valueStr} with no significant movement. Conditions appear stable for now.`;
    }
  }

  // ── Crypto: price + momentum ──
  if (primary && primary.sourceFamily === "crypto_market") {
    const name = String(primary.metadata?.name ?? "This asset");
    const price = Number(primary.currentValue);
    const priceStr = price >= 1 ? `$${price.toLocaleString("en-US", { maximumFractionDigits: 0 })}` : `$${price.toFixed(4)}`;

    if (dir === "up") return `${name} is trading at ${priceStr} and showing upward momentum. Market sentiment is leaning positive.`;
    if (dir === "down") return `${name} is at ${priceStr} and under pressure. Sellers are currently in control.`;
    return `${name} is trading around ${priceStr}. No clear direction right now — the market is in wait-and-see mode.`;
  }

  // ── Prediction markets: probability as outlook ──
  if (primary && (primary.sourceFamily === "prediction_market" || primary.sourceFamily === "forecast_aggregator")) {
    const prob = Number(primary.currentValue);
    const pct = Math.round(prob * 100);
    const question = String(primary.metadata?.question ?? "");

    if (pct >= 70) return `Markets are pricing this at ${pct}% likely. The consensus is leaning strongly toward yes.`;
    if (pct >= 50) return `Trading at ${pct}% probability. Slight lean toward yes, but far from certain.`;
    if (pct >= 30) return `Only ${pct}% probability in prediction markets. The consensus leans toward no.`;
    return `Markets see this as unlikely — just ${pct}% probability. Very few are betting on it.`;
  }

  // ── Sports odds: implied probability ──
  if (primary && primary.sourceFamily === "sports_odds") {
    const prob = Number(primary.currentValue);
    const pct = Math.round(prob * 100);
    if (pct >= 60) return `Bookmakers give this a ${pct}% chance. The odds are clearly in favor.`;
    if (pct >= 40) return `Bookmakers see this as a toss-up — roughly ${pct}% implied probability.`;
    return `The betting odds suggest this is unlikely at ${pct}%. The field is wide open.`;
  }

  // ── Hazard/weather: situation description ──
  if (primary && primary.sourceFamily === "hazard_weather") {
    if (primary.signalType === "earthquake_magnitude") {
      const mag = Number(primary.currentValue);
      if (mag >= 5) return `A significant earthquake (M${mag.toFixed(1)}) was recently recorded. Elevated seismic activity this week.`;
      if (signalCount > 50) return `${signalCount} earthquakes recorded recently. Activity levels appear normal — no unusual patterns detected.`;
      return `Moderate seismic activity this week with ${signalCount} events recorded. Nothing out of the ordinary.`;
    }
    if (primary.signalType === "weather_severity") {
      const severity = Number(primary.currentValue);
      if (severity >= 3) return `Severe weather alerts are active. Conditions may be dangerous in affected areas.`;
      return `Weather alerts are active but conditions are manageable. Stay informed if you're in an affected area.`;
    }
  }

  // ── Political/legislative: action description ──
  if (primary && primary.sourceFamily === "political_official") {
    if (signalCount >= 3) return `Multiple legislative actions detected recently. Congress is actively working on this issue.`;
    return `Limited legislative activity right now. This issue is not seeing much movement in Congress.`;
  }

  // ── DeFi: TVL as market health ──
  if (primary && primary.sourceFamily === "defi_signal") {
    const tvl = Number(primary.currentValue);
    const tvlStr = tvl >= 1e9 ? `$${(tvl / 1e9).toFixed(1)}B` : `$${(tvl / 1e6).toFixed(0)}M`;
    return `Total value locked is at ${tvlStr}. ${dir === "up" ? "Capital is flowing in — a positive signal." : dir === "down" ? "Capital is flowing out — a cautious signal." : "Holding steady for now."}`;
  }

  // ── Universal fallback: topic-aware, not generic ──
  const topicLabel = topicName ? topicName.toLowerCase() : "this topic";
  if (dir === "up") return `Signals are pointing upward on ${topicLabel}. Multiple indicators suggest positive momentum.`;
  if (dir === "down") return `Signals are trending downward on ${topicLabel}. The data suggests a negative direction.`;
  if (signalCount > 10) return `Tracking ${signalCount} data points on ${topicLabel}. The picture is stable with no significant movement.`;
  if (signalCount > 0) return `Early signals are coming in on ${topicLabel} but no clear trend has emerged yet.`;
  return `We're watching ${topicLabel} across multiple sources. No strong signals yet, but we're tracking this.`;
}

// ── Expert Line Generation (Synthesis) ──────────────────────────────────
// Produces a single sentence that synthesizes what multiple sources say.
// Only mentions supporting families if they contributed meaningful signals.

function generateExpertLine(
  signals: ScoredSignal[],
  pack: SourcePack,
  questionType: QuestionType,
  direction: string,
  confidence: number,
): string | null {
  const families = new Map<string, ScoredSignal[]>();
  for (const s of signals) {
    const list = families.get(s.sourceFamily) ?? [];
    list.push(s);
    families.set(s.sourceFamily, list);
  }

  const predictiveSignals = signals.filter((s) => pack.predictiveSpine.includes(s.sourceFamily));
  const strengtheningSignals = signals.filter((s) => pack.strengtheningLayer.includes(s.sourceFamily));

  // Competition: leader + gap
  if (questionType === "competition") {
    const ranking = extractCompetitionRanking(signals);
    const first = ranking[0] ?? null;
    const second = ranking[1] ?? null;
    if (first && second) {
      const gap = first.pct - second.pct;
      if (gap < 5) return `${first.name} and ${second.name} are separated by just ${gap} points.`;
      if (gap < 15) return `${first.name} leads ${second.name} by ${gap} points.`;
      return `${first.name} is pulling away with a ${gap}-point lead.`;
    }
    if (first) return `${first.name} leads at ${first.pct}%.`;
    return null;
  }

  // Threshold: spine (market view) + strengthening (official data)
  if (questionType === "threshold") {
    const metric = strengtheningSignals.find((s) =>
      s.sourceFamily === "macro_official" || s.sourceFamily === "crypto_market",
    );
    const market = predictiveSignals.find((s) =>
      s.signalType === "market_probability" || s.signalType === "forecast_probability",
    );
    if (metric && market) {
      const prob = Math.round(market.currentValue * 100);
      return `Currently at ${formatMetricValue(metric)}. Markets give it ${prob}% odds of reaching target.`;
    }
    if (metric) return `Currently at ${formatMetricValue(metric)}. Market view not yet available.`;
    if (market) {
      const prob = Math.round(market.currentValue * 100);
      return `Markets say ${prob}% chance. Official data not yet connected.`;
    }
    return null;
  }

  // Binary: predictive spine consensus + strengthening context
  const probSignals = predictiveSignals.filter((s) =>
    s.signalType === "market_probability" || s.signalType === "forecast_probability",
  );

  if (probSignals.length > 0) {
    const avgProb = probSignals.reduce((sum, s) => sum + s.currentValue, 0) / probSignals.length;
    const pct = Math.round(avgProb * 100);

    // Only mention strengthening layer if it actually contributed meaningful signals
    const meaningfulStrengthening = strengtheningSignals.filter((s) => s.currentValue !== null);
    if (meaningfulStrengthening.length > 0) {
      const stFamilies = [...new Set(meaningfulStrengthening.map((s) => s.sourceFamily))];
      const supporting = stFamilies.map((f) => FAMILY_DISPLAY[f] ?? f).join(" and ");
      return `Markets say ${pct}% yes, grounded by ${supporting}.`;
    }

    const platforms = new Set(probSignals.map((s) => s.sourceName));
    if (platforms.size >= 2) {
      return `Markets say ${pct}% yes across ${platforms.size} platforms.`;
    }
    return `Markets say ${pct}% yes. Context sources still thin.`;
  }

  return `Tracking across ${families.size} source types.`;
}

function formatMetricValue(signal: ScoredSignal): string {
  if (signal.sourceFamily === "crypto_market") {
    const price = signal.currentValue;
    return price >= 1
      ? `$${price.toLocaleString("en-US", { maximumFractionDigits: 0 })}`
      : `$${price.toFixed(4)}`;
  }
  if (signal.sourceFamily === "macro_official") {
    const v = signal.currentValue;
    return v > 100 ? v.toLocaleString("en-US") : `${v.toFixed(2)}%`;
  }
  return signal.currentValue.toLocaleString("en-US", { maximumFractionDigits: 2 });
}

// ── Competition Ranking Extraction ──────────────────────────────────────
// Extracts ranked contenders from market signals for competition questions.

function stripArticle(name: string): string {
  return name.replace(/^(the|a|an)\s+/i, "");
}

function extractEntityName(question: string): string | null {
  const patterns = [
    /^Will (.+?) win\b/i,
    /^Will (.+?) have the best\b/i,
    /^Will (.+?) (?:lead|be the|dominate|finish)\b/i,
    /^(.+?) to win\b/i,
    /^Will (.+?) (?:win|beat|reach|hit|score|qualify|advance|place|rank)\b/i,
  ];
  for (const pattern of patterns) {
    const match = question.match(pattern);
    const captured = match?.[1];
    if (captured) return stripArticle(captured.trim());
  }
  return null;
}

// Individual award keywords -- markets with these are about player awards, not team championships
const INDIVIDUAL_AWARD_PATTERN = /\b(mvp|most valuable|scoring title|assists leader|rebounds|defensive player|rookie of the year|sixth man|all[- ]star|ballon d'or|golden boot|golden glove|driver of the day|pole position|fastest lap)\b/i;

function extractCompetitionRanking(
  signals: ScoredSignal[],
): Array<{ name: string; pct: number }> {
  const contenders = signals
    .filter(
      (s) =>
        s.sourceFamily === "prediction_market" ||
        s.sourceFamily === "forecasting" ||
        s.sourceFamily === "sports_odds",
    )
    .map((s) => {
      const q = String(s.metadata?.question ?? "");
      // Skip individual award markets (MVP, scoring title, etc.)
      if (INDIVIDUAL_AWARD_PATTERN.test(q)) return null;
      const extracted = extractEntityName(q);
      if (!extracted) return null;
      const pct = Math.round(s.currentValue * 100);
      return { name: extracted, pct };
    })
    .filter((c): c is { name: string; pct: number } => c !== null && c.pct > 0)
    .sort((a, b) => b.pct - a.pct);

  // Deduplicate
  const seen = new Set<string>();
  return contenders.filter((c) => {
    const key = c.name.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
