/** ISO 3166-1 alpha-2 → display name for top countries by likely user base */
export const COUNTRY_NAMES: Record<string, string> = {
  AF: "Afghanistan",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  BD: "Bangladesh",
  BE: "Belgium",
  BR: "Brazil",
  CA: "Canada",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  CZ: "Czech Republic",
  DK: "Denmark",
  EG: "Egypt",
  FI: "Finland",
  FR: "France",
  DE: "Germany",
  GR: "Greece",
  HK: "Hong Kong",
  HU: "Hungary",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JP: "Japan",
  JO: "Jordan",
  KE: "Kenya",
  KR: "South Korea",
  KW: "Kuwait",
  LB: "Lebanon",
  MY: "Malaysia",
  MX: "Mexico",
  NL: "the Netherlands",
  NZ: "New Zealand",
  NG: "Nigeria",
  NO: "Norway",
  PK: "Pakistan",
  PH: "the Philippines",
  PL: "Poland",
  PT: "Portugal",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russia",
  SA: "Saudi Arabia",
  SG: "Singapore",
  ZA: "South Africa",
  ES: "Spain",
  SE: "Sweden",
  CH: "Switzerland",
  TW: "Taiwan",
  TH: "Thailand",
  TR: "Turkey",
  UA: "Ukraine",
  AE: "the UAE",
  GB: "the United Kingdom",
  US: "the United States",
  VN: "Vietnam",
};

/** Get display-friendly country name from ISO alpha-2 code */
export function getCountryDisplayName(code: string): string | null {
  return COUNTRY_NAMES[code.toUpperCase()] ?? null;
}
